name: 1-Checkout-Build-Artifact

# This workflow will checkout the code, ZIP the Python file, and create an artifact for use in following workflows.
on:
  # Enables manual runs
  workflow_dispatch:
  # Runs "Every day at 4:05" (see https://crontab.guru)
  schedule:
  - cron: "5 4 * * *"

jobs:
  Checkout-Artifact-Scan:
    runs-on: [ubuntu-latest]
    steps:

# Checkout
      - uses: actions/checkout@v2
            
# Create application artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: petstore-api-python
          path: ./**         
     
# Use the UploadAndScan action to submit the artifact for scanning
      - name: Veracode Upload and Scan Action Step
        uses: veracode/veracode-uploadandscan-action@master
        id: upload_and_scan
        with:
          appname: 'PetstoreAPI-Python-GitHub'
          createprofile: true
          version: '${{ github.run_id }}'
          criticality: High
          filepath: 'petstore-api-python.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          teams: 'ClintPollock-DemoApps2023'
        continue-on-error: true
